create table if not exists route_network(
network_id Integer not null,
network_name Integer null,
public_network varchar(255) null,
default_vpc varchar(255) null,
private_network varchar(255) null,
subnets_count varchar(255) null,
public_subnet varchar(255) null,
private_subnet varchar(255) null,
internet_gateway varchar(255) null,
nat_gateway varchar(255) null,
vpc_peering varchar(255) null,
end_point varchar(255) null,
vpc_flow_log varchar(255) null,
direct_connect varchar(255) null,
constraint route_network_pk primary key(network_id));